# openshift_mtv: https://forklift-inventory-openshift-mtv.apps.jv5pc.dynamic.redhatworkshops.io
openshift_mtv: https://forklift-inventory-openshift-mtv.apps.cluster-fkrcs-1.dynamic.redhatworkshops.io
openshift_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35323665616166656661316335383231306539666461333731333434616539326334383234656630
          6230366265643535376466633861646361353666623862310a393931363833633830313933316563
          35323532386463356334336337333166366538643030666533633832333036313434353763376132
          3432306534326462390a383236376665336666666437313939386232326133356539336265653130
          39336437633661646165363039376531303463313434646232613532316436333661613530613534
          36643961653534656638366334343762663239373735326134646565353763653237353932303736
          353864636136613031356134653539613339
