# openshift_mtv: https://forklift-inventory-openshift-mtv.apps.jv5pc.dynamic.redhatworkshops.io
openshift_mtv: https://forklift-inventory-openshift-mtv.apps.cluster-2jj7q.dynamic.redhatworkshops.io
openshift_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62336164656332623339333735353932626232306662326637363631663238323836343838353863
          3030356637303537306638613938666430396436363663340a303632303337633131386361353534
          33373862356636323339343361363133653366643933333333396264636335656664396239643433
          3734383237626365310a373333613237303861313530343764613538393262616231653665376331
          66366131666638636131366264386537313437343165636539303030393630393266356365353436
          31366364623338616330653134386638613732383931656230333339623463346562306334653234
          643065333934313032303362623136613732
