---
servicenow_hostname: https://dev280409.service-now.com
servicenow_username: admin
servicenow_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39643866343539343239306136613239323564346461383865636665386262316261383663356266
          3864383232323163386531323766303831623838336630340a346339373965663864323565636531
          33383030323634326134343534383036633835653163333539373835333731363733643231333936
          6435303730333966390a373430373365653432323335353939616138646232313365373230633766
          6162
close_code: 'successful'
close_notes: "Successfully migrated"
cr_short_description: 'VMware Migration'